service: duomly-serverless-course

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  environment:
    JWT_SECRET: ${file(./secrets.json):JWT_SECRET}
    DB: ${file(./secrets.json):DB}
    PAYMENT_VENDOR: ${file(./secrets.json):PAYMENT_VENDOR}
    PAYMENT_AUTH: ${file(./secrets.json):PAYMENT_AUTH}
    PAYMENT_YEARLY: ${file(./secrets.json):PAYMENT_YEARLY}
    PAYMENT_MONTHLY: ${file(./secrets.json):PAYMENT_MONTHLY}
    PAYMENT_RETURN: ${file(./secrets.json):PAYMENT_RETURN}

functions:
  verify-jwt:
    handler: authentication/VerifyJWT.verify

  login:
    handler: authentication/AuthenticationHandler.login
    events:
      - http:
          path: auth/login
          method: post
          cors: true

  register:
    handler: authentication/AuthenticationHandler.register
    events:
      - http:
          path: auth/register
          method: post
          cors: true

  myProfile:
    handler: user/UserHandler.myProfile
    events:
      - http:
          path: user/myprofile
          method: get
          cors: true
          authorizer: verify-jwt

  createOrder:
    handler: order/OrderHandler.create
    events:
      - http:
          path: order/create
          method: post
          cors: true
          authorizer: verify-jwt

  myOrders:
    handler: order/OrderHandler.myOrders
    events:
      - http:
          path: order/my
          method: get
          cors: true
          authorizer: verify-jwt

  handlePaymentWebhook:
    handler: order/OrderHandler.webhook
    events:
      - http:
          path: order/webhook
          method: post
          cors: true
